### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by GeekAlexis** [ozantezcan/BSUV-Net-2.0#5]
Thanks for the great work! 

Is this the official implementation of BSUV-NET 2.0? 
Are there pretrained BSUV-NET 2.0 and fast BSUV-NET 2.0 that I can quickly test on my own data?

**Comment by ozantezcan** [comment]
Hi! Thanks for your interest in this work. I will upload weights of BSUV-NET 2.0 and fast BSUV-NET 2.0 within the next couple of days. In the meantime, you can use [BSUV-Net-inference repo](https://github.com/ozantezcan/BSUV-Net-inference) to test your data on BSUV-Net. The network architecture of  BSUV-Net is exactly the same as  BSUV-Net 2.0. The only difference is the network weights.

**Comment by GeekAlexis** [comment]
Many thanks. I have tested the original BSUV-Net and I'm looking forward to the 2.0 version.

**Comment by ozantezcan** [comment]
Thanks for your patience. I added the trained models for 2.0 version to [BSUV-Net-inference repo](https://github.com/ozantezcan/BSUV-Net-inference). You need to pull the most recent version of the repo to be able to use new model files. I hope that helps. Let me know if you have any questions.

**Comment by GeekAlexis** [comment]
@ozantezcan Is there any confidence threshold to lower the sensitivity of the model during inference?

**Comment by ozantezcan** [comment]
You can add a threshold to the BGS predictions. For example, you can add the following after [this line](https://github.com/ozantezcan/BSUV-Net-inference/blob/master/inference.py#L48).

`bgs_pred  = (bgs_pred < threshold) * 1`

By tuning the threshold, you should be able to change the sensitivity. I hope that works for you.

**Comment by GeekAlexis** [comment]
Thank you, that works
