### ISSUE TITLE
missing currentFr in GoogleDrive

### ISSUE THREAD

**Issue by sbreuers** [ozantezcan/BSUV-Net-2.0#7]
Hey there,
it seems like the "currentFr" folder is missing in the linked GoogleDrive or can it be found elsewhere?

**Comment by ozantezcan** [comment]
"currentFr" is the original change detection dataset. Since that dataset does not belong to me, I did not put it in my GDrive. You need to download the dataset from http://changedetection.net/ and unzip it to `./dataset/currentFr`. Let me know if you run any issues.

**Comment by sbreuers** [comment]
Makes sense! unzipped the dataset to the correct path now! Thanks for the quick help!
